steps:
  # 1. Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    dir: 'backend'

  # 2. Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    dir: 'backend'

  # 3. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_URI/backend:$COMMIT_SHA'
      - '.'
    dir: 'backend'

  # 4. Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_URI/backend:$COMMIT_SHA'

  # 5. Scan image with Trivy (now using Artifact Registry image)
  - name: 'aquasec/trivy:0.45.1'
    args:
      - 'image'
      - '--exit-code'
      - '1'
      - '--no-progress'
      - '--severity'
      - 'HIGH,CRITICAL'
      - '$_AR_URI/backend:$COMMIT_SHA'

  # 6. Update secret with commit SHA (optional)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "GIT_COMMIT_SHA=$COMMIT_SHA" | gcloud secrets versions add git-commit-sha --data-file=-
    secretEnv: ['GCP_PROJECT']

  # 7. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s/backend-deployment.yaml'
      - '--image=$_AR_URI/backend:$COMMIT_SHA'
      - '--cluster=sample-autopilot'
      - '--location=us-central1'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    secretEnv: ['GCP_PROJECT']

substitutions:
  _AR_URI: 'us-central1-docker.pkg.dev/my-gke-project-473809/my-repo'
  _COMMIT_SHA: '$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/my-gke-project-473809/secrets/project-id/versions/latest
      env: 'GCP_PROJECT'

images:
  - '$_AR_URI/backend:$COMMIT_SHA'
