steps:
  # 1. Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    dir: 'backend'

  # 2. Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    dir: 'backend'

  # 3. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - "$_AR_URI/backend:$COMMIT_SHA"
      - '.'
    dir: 'backend'

  # 4. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - "$_AR_URI/backend:$COMMIT_SHA"

  # 5. Dummy step to reference GCP key volume
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'ls /workspace/key.json'
    volumes:
      - name: 'gcp-key'
        path: '/workspace/key.json'
    secretEnv: ['GCP_KEY_JSON']

  # 6. Scan image with Trivy
  - name: 'aquasec/trivy:0.45.1'
    args:
      - 'image'
      - '--exit-code'
      - '1'
      - '--no-progress'
      - '--scanners'
      - 'vuln'
      - '--severity'
      - 'HIGH,CRITICAL'
      - '--ignorefile'
      - '/workspace/backend/.trivyignore'
      - "$_AR_URI/backend:$COMMIT_SHA"
    dir: 'backend'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/key.json'
    volumes:
      - name: 'gcp-key'
        path: '/workspace/key.json'
    secretEnv: ['GCP_KEY_JSON']

  # 7. Update secret with commit SHA
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "GIT_COMMIT_SHA=$COMMIT_SHA" | gcloud secrets versions add git-commit-sha --data-file=-
    secretEnv: ['GCP_PROJECT']

  # 8. Set IMAGE environment variable for gke-deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'set-image-variable'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export IMAGE="$_AR_URI/backend:$COMMIT_SHA"
        echo "IMAGE=$IMAGE" >> $BUILD_ENV_FILE
    env:
      - 'COMMIT_SHA'
      - '_AR_URI'

  # 9. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s/backend-deployment.yaml'
      - '--image=$IMAGE'
      - '--cluster=sample-autopilot'
      - '--location=us-central1'
      - '--namespace=default'
    env:
      - 'IMAGE'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    secretEnv: ['GCP_PROJECT']

substitutions:
  _AR_URI: us-central1-docker.pkg.dev/my-gke-project-473809/my-repo

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/my-gke-project-473809/secrets/project-id/versions/latest
      env: 'GCP_PROJECT'
    - versionName: projects/my-gke-project-473809/secrets/cloudbuild-sa-key/versions/latest
      env: 'GCP_KEY_JSON'

images:
  - "$_AR_URI/backend:$COMMIT_SHA"
