steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    dir: 'frontend'
  # Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']
    dir: 'frontend'
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_URI/frontend:$COMMIT_SHA'
      - '.'
    dir: 'frontend'
  # Scan for vulnerabilities
  - name: 'aquasec/trivy:0.45.1'
    args:
      - 'image'
      - '--exit-code'
      - '1'
      - '--no-progress'
      - '--severity'
      - 'HIGH,CRITICAL'
      - '$_AR_URI/frontend:$COMMIT_SHA'
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_URI/frontend:$COMMIT_SHA']
  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=k8s/frontend-deployment.yaml'
      - '--image=frontend=$_AR_URI/frontend:$COMMIT_SHA'
      - '--cluster=app-cluster'
      - '--location=us-central1'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    secretEnv: ['GCP_PROJECT']

substitutions:
  _AR_URI: 'us-central1-docker.pkg.dev/my-gke-project-473809/app-repo'
  _COMMIT_SHA: '$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  timeout: '1800s'

availableSecrets:
  secretManager:
    - versionName: projects/my-gke-project-473809/secrets/project-id/versions/latest
      env: 'GCP_PROJECT'

images:
  - '$_AR_URI/frontend:$COMMIT_SHA'