   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: backend
     namespace: default
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: backend
     template:
       metadata:
         labels:
           app: backend
       spec:
         containers:
         - name: backend
           image: us-central1-docker.pkg.dev/my-gke-project-473809/my-repo/backend:c82ae3db22cf63542130e0b2d13650ac94fd6653
           ports:
           - containerPort: 3000
           resources:
             requests:
               cpu: 100m
               memory: 128Mi
             limits:
               cpu: 200m
               memory: 512Mi
           livenessProbe:
             httpGet:
               path: /api/health
               port: 3000
             initialDelaySeconds: 30
             periodSeconds: 10
           readinessProbe:
             httpGet:
               path: /api/health
               port: 3000
             initialDelaySeconds: 5
             periodSeconds: 5
           env:
           - name: PORT
             value: "3000"
           - name: GCP_REGION
             value: "us-central1"
           - name: GIT_COMMIT_SHA
             valueFrom:
               secretKeyRef:
                 name: backend-secrets
                 key: git-commit-sha
