apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/my-gke-project-473809/secrets/git-commit-sha/versions/latest"
        fileName: "GIT_COMMIT_SHA"